"""index approvals status and requested_at

Revision ID: 0853ac85c2a8
Revises: 3d71173dfd55
Create Date: 2026-09-12 04:36:59.658370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0853ac85c2a8'
down_revision = '3d71173dfd55'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_approvals_status_requested_at', 'approvals', ['status', 'requested_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_approvals_status_requested_at', table_name='approvals')
    # ### end Alembic commands ###
